### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by realivanjx** [timob/jnigi#23]
Hi,

I got this error when trying to install this library:

![image](https://user-images.githubusercontent.com/12814796/75506407-81b01a80-5a10-11ea-86dc-daf9a8bfe56c.png)

Any help will be appreciated.
Thanks

**Comment by timob** [comment]
Can you try changing line 7 of the `install.bat` , replacing the slashes with back slashes.
It should look like:
```
set CGO_CFLAGS=-I%jdkpath%\include -I%jdkpath%\include\win32
```

And try running it again.

**Comment by timob** [comment]
Also you might want to try removing the `"` quotes on the command line.

**Comment by realivanjx** [comment]
Thanks for the fast response.
Unfortunately it still has the same issue.

![image](https://user-images.githubusercontent.com/12814796/75507746-88409100-5a14-11ea-9ec8-f16063be4b17.png)

**Comment by timob** [comment]
In the output:
```
Files\Java\jdk1.8.0_201"\include
```
That `"` seems to be the problem. Not sure how that is getting there, maybe try just using the path as the argument with no quotes: 
```
.\install.bat C:\Program Files\Java\jdk1.8.0_201
```

**Comment by realivanjx** [comment]
OK now it gives other error.

![image](https://user-images.githubusercontent.com/12814796/75508349-5f210000-5a16-11ea-8a2a-8af2412fd031.png)

Maybe thats because the cli only reads the "C:\Program". AFAIK to have space in path u must use the "

**Comment by timob** [comment]
Can you change line 9 of `install.bat` to:
```
go install -x
```
This will print out the commands cgo is using to compile the generated C files. You can look for the `-I` arguments in the lines printed to see if they look right.

**Comment by realivanjx** [comment]
here you go

```
PS C:\Users\Ivan Kara\Documents\projects\jnigi> .\install.bat $env:java_home                                            WORK=C:\Users\IVANKA~1\AppData\Local\Temp\go-build829512026
mkdir -p $WORK\b032\
cd C:\Go\src\runtime\cgo
CGO_LDFLAGS='"-g" "-O2"' "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build829512026\\b032\\" -importpath runtime/cgo -import_runtime_cgo=false -import_syscall=false -- -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build829512026\\b032\\" "-I\"C:\\Program" "Files\\Java\\jdk1.8.0_201\"\\include" "-I\"C:\\Program" "Files\\Java\\jdk1.8.0_201\"\\include\\win32" -Wall -Werror "C:\\Go\\src\\runtime\\cgo\\cgo.go"
# runtime/cgo
gcc: error: Files\Java\jdk1.8.0_201"\include: No such file or directory
gcc: error: Files\Java\jdk1.8.0_201"\include\win32: No such file or directory
PS C:\Users\Ivan Kara\Documents\projects\jnigi> .\install.bat C:\Program Files\Java\jdk1.8.0_201                        WORK=C:\Users\IVANKA~1\AppData\Local\Temp\go-build288751402
mkdir -p $WORK\b001\
cd C:\Users\Ivan Kara\Documents\projects\jnigi
CGO_LDFLAGS='"-g" "-O2"' "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build288751402\\b001\\" -importpath _/C_/Users/Ivan_Kara/Documents/projects/jnigi -- -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build288751402\\b001\\" "-IC:\\Program\\include" "-IC:\\Program\\include\\win32" "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi\\cinit.go" "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi\\cmem.go" "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi\\cwrapper.go" "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi\\windows.go"
# _/C_/Users/Ivan_Kara/Documents/projects/jnigi
.\cinit.go:8:16: fatal error: jni.h: No such file or directory
 #include<jni.h>
                ^
compilation terminated.
PS C:\Users\Ivan Kara\Documents\projects\jnigi>
```

**Comment by realivanjx** [comment]
I think the only workaround is to create a symlink. I suppose this is a success?

```
mklink /J c:\jdk "C:\Program Files\Java\jdk1.8.0_201\"
```

```
PS C:\Users\Ivan Kara\Documents\projects\jnigi> .\install.bat c:\jdk                                                    WORK=C:\Users\IVANKA~1\AppData\Local\Temp\go-build361646006
mkdir -p $WORK\b032\
cd C:\Go\src\runtime\cgo
CGO_LDFLAGS='"-g" "-O2"' "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" -importpath runtime/cgo -import_runtime_cgo=false -import_syscall=false -- -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -Wall -Werror "C:\\Go\\src\\runtime\\cgo\\cgo.go"
cd $WORK
gcc -fno-caret-diagnostics -c -x c - || true
gcc -Qunused-arguments -c -x c - || true
gcc -fdebug-prefix-map=a=b -c -x c - || true
gcc -gno-record-gcc-switches -c -x c - || true
cd $WORK\b032
TERM='dumb' gcc -I "C:\\Go\\src\\runtime\\cgo" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -Wall -Werror -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x001.o" -c _cgo_export.c
TERM='dumb' gcc -I "C:\\Go\\src\\runtime\\cgo" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -Wall -Werror -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x002.o" -c cgo.cgo2.c
cd C:\Go\src\runtime\cgo
TERM='dumb' gcc -I "C:\\Go\\src\\runtime\\cgo" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -Wall -Werror -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x003.o" -c gcc_context.c
TERM='dumb' gcc -I "C:\\Go\\src\\runtime\\cgo" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -Wall -Werror -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x004.o" -c gcc_libinit_windows.c
TERM='dumb' gcc -I "C:\\Go\\src\\runtime\\cgo" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -Wall -Werror -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x005.o" -c gcc_util.c
TERM='dumb' gcc -I "C:\\Go\\src\\runtime\\cgo" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -Wall -Werror -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x006.o" -c gcc_windows_amd64.c
TERM='dumb' gcc -I "C:\\Go\\src\\runtime\\cgo" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -Wall -Werror -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x007.o" -c gcc_amd64.S
cd $WORK\b032
TERM='dumb' gcc -I "C:\\Go\\src\\runtime\\cgo" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -Wall -Werror -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_cgo_main.o" -c _cgo_main.c
cd C:\Go\src\runtime\cgo
TERM='dumb' gcc -I "C:\\Go\\src\\runtime\\cgo" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032=/tmp/go-build" -gno-record-gcc-switches -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_cgo_.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_cgo_main.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x001.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x002.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x003.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x004.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x005.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x006.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x007.o" -g -O2
TERM='dumb' "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -dynpackage cgo -dynimport "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_cgo_.o" -dynout "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_cgo_import.go" -dynlinker
cat >$WORK\b032\importcfg << 'EOF' # internal
# import config
EOF
"C:\\Go\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_pkg_.a" -trimpath "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032" -p runtime/cgo -std -buildid P99nkJkfhHD5d1pOTNr_/P99nkJkfhHD5d1pOTNr_ -goversion go1.11.5 -D "" -importcfg "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\importcfg" -pack -asmhdr "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\go_asm.h" -c=4 "C:\\Go\\src\\runtime\\cgo\\callbacks.go" "C:\\Go\\src\\runtime\\cgo\\iscgo.go" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_cgo_gotypes.go" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\cgo.cgo1.go" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_cgo_import.go"
"C:\\Go\\pkg\\tool\\windows_amd64\\asm.exe" -trimpath "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032" -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\" -I "C:\\Go\\pkg\\include" -D GOOS_windows -D GOARCH_amd64 -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\asm_amd64.o" "C:\\Go\\src\\runtime\\cgo\\asm_amd64.s"
"C:\\Go\\pkg\\tool\\windows_amd64\\pack.exe" r "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_pkg_.a" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\asm_amd64.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x001.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x002.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x003.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x004.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x005.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x006.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_x007.o" # internal
"C:\\Go\\pkg\\tool\\windows_amd64\\buildid.exe" -w "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_pkg_.a" # internal
cp "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b032\\_pkg_.a" "C:\\Users\\Ivan Kara\\AppData\\Local\\go-build\\81\\8151116327326e87e390de3aa9b9d3d28ddc1c8d10919772bacfdee1b79e6d26-d" # internal
mkdir -p $WORK\b001\
cd C:\Users\Ivan Kara\Documents\projects\jnigi
CGO_LDFLAGS='"-g" "-O2"' "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\" -importpath _/C_/Users/Ivan_Kara/Documents/projects/jnigi -- -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi\\cinit.go" "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi\\cmem.go" "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi\\cwrapper.go" "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi\\windows.go"
cd $WORK\b001
TERM='dumb' gcc -I "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x001.o" -c _cgo_export.c
TERM='dumb' gcc -I "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x002.o" -c cinit.cgo2.c
TERM='dumb' gcc -I "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x003.o" -c cmem.cgo2.c
TERM='dumb' gcc -I "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x004.o" -c cwrapper.cgo2.c
TERM='dumb' gcc -I "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x005.o" -c windows.cgo2.c
TERM='dumb' gcc -I "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\" "-Ic:\\jdk\\include" "-Ic:\\jdk\\include\\win32" -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_cgo_main.o" -c _cgo_main.c
cd C:\Users\Ivan Kara\Documents\projects\jnigi
TERM='dumb' gcc -I "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001=/tmp/go-build" -gno-record-gcc-switches -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_cgo_.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_cgo_main.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x001.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x002.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x003.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x004.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x005.o" -g -O2
TERM='dumb' "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -dynpackage jnigi -dynimport "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_cgo_.o" -dynout "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_cgo_import.go"
cat >$WORK\b001\importcfg << 'EOF' # internal
# import config
packagefile errors=C:\Go\pkg\windows_amd64\errors.a
packagefile fmt=C:\Go\pkg\windows_amd64\fmt.a
packagefile log=C:\Go\pkg\windows_amd64\log.a
packagefile os=C:\Go\pkg\windows_amd64\os.a
packagefile path=C:\Go\pkg\windows_amd64\path.a
packagefile runtime=C:\Go\pkg\windows_amd64\runtime.a
packagefile strings=C:\Go\pkg\windows_amd64\strings.a
packagefile runtime/cgo=$WORK\b032\_pkg_.a
packagefile syscall=C:\Go\pkg\windows_amd64\syscall.a
EOF
"C:\\Go\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_pkg_.a" -trimpath "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001" -p _/C_/Users/Ivan_Kara/Documents/projects/jnigi -buildid zHOMwagwYAv9fFeC-S8q/zHOMwagwYAv9fFeC-S8q -goversion go1.11.5 -D _/C_/Users/Ivan_Kara/Documents/projects/jnigi -importcfg "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\importcfg" -pack -c=4 "C:\\Users\\Ivan Kara\\Documents\\projects\\jnigi\\jnigi.go" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_cgo_gotypes.go" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\cinit.cgo1.go" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\cmem.cgo1.go" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\cwrapper.cgo1.go" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\windows.cgo1.go" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_cgo_import.go"
"C:\\Go\\pkg\\tool\\windows_amd64\\pack.exe" r "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_pkg_.a" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x001.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x002.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x003.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x004.o" "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_x005.o" # internal
"C:\\Go\\pkg\\tool\\windows_amd64\\buildid.exe" -w "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_pkg_.a" # internal
cp "C:\\Users\\IVANKA~1\\AppData\\Local\\Temp\\go-build361646006\\b001\\_pkg_.a" "C:\\Users\\Ivan Kara\\AppData\\Local\\go-build\\53\\53d120ebb12906941bd29471824fba0aa1e75e7f054faaf3b8c8166212be3d5e-d" # internal
PS C:\Users\Ivan Kara\Documents\projects\jnigi> 
```

**Comment by timob** [comment]
Looks like that fixed it.

It's something to do with the quoting and the batch file. I don't have access to a windows machine right now. When I do I will try to fix this.

**Comment by realivanjx** [comment]
Hi, one more issue after installing i cant use it for my project. Here is what it says:

```
PS C:\Users\Ivan Kara\Documents\projects\at-test> go run .\main.go
main.go:4:8: cannot find package "github.com/timob/jnigi" in any of:
        C:\Go\src\github.com\timob\jnigi (from $GOROOT)
        C:\Users\Ivan Kara\go\src\github.com\timob\jnigi (from $GOPATH)
PS C:\Users\Ivan Kara\Documents\projects\at-test>
```

Thanks.

**Comment by timob** [comment]
Thats not due to the package. I would check those paths that the error mentions to see if the package is present.

**Comment by realivanjx** [comment]
i instead cloned to the `$GOPATH/src/github.com` and executed `install.bat` there and it seems to be working.

**Comment by timob** [comment]
I've tried running tests/build example code on windows using the compilevars.sh script. I have java installed in `c:\java\jdk8u212-b03`.

```
C:\msys64\home\user\repos\gorepos\src\github.com\timob\jnigi>compilevars.bat c:\java\jdk8u212-b03
C:\msys64\home\user\repos\gorepos\src\github.com\timob\jnigi>go test
WARNING: JNI local refs: zu, exceeds capacity: zu
        at java.lang.System.initProperties(Native Method)
        at java.lang.System.initializeSystemClass(System.java:1166)
PASS
ok      github.com/timob/jnigi  0.196s

C:\msys64\home\user\repos\gorepos\src\github.com\timob\jnigi>
```

I am using `cmd.exe`. The issues you had may be because you are using Powershell.

**Comment by timob** [comment]
I just tried using a path with spaces in it, and it same problems as in the original post. To fix you have to double backslash the spaces.
For example:
```
compilevars.bat c:\java\\ -\\ Copy\jdk8u212-b03
```

**Comment by timob** [comment]
Please open another issue if you still have a problem.
